project:
  type: website
  output-dir: docs

website:
  title: "AAI1001 Lab"
  navbar:
    left:
      - href: week_01_lab_note.qmd
        text: Week 1
      - href: week_02_lab_note.qmd
        text: Week 2
      - href: week_03_lab_note.qmd
        text: Week 3
      - href: week_04_lab_note.qmd
        text: Week 4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



