project:
  type: website
  output-dir: docs

website:
  title: "Week 3 Lab"
  navbar:
    left:
      - href: week_03_lab_note.qmd
        text: Week 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



